
name: FAST_API ORM Xushnud
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "DB_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DATABASE_PORT }}" >> .env

      - name: Test with pytest
        run: |
          pytest
